version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: echaspoint-nginx-container
    ports:
      - "8071:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php
    container_name: echaspoint-php-container
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=mysql
      - DB_NAME=slim4_api_skeleton
      - DB_USER=root
      - DB_PASS=
      - DB_PORT=3306

    volumes:
     - ./:/var/www/html

volumes:
  my-data:
