version: '3.8'

networks:
  kong-net:
    external: true  # Usa la misma red externa

services:
  user-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    container_name: user-service
    networks:
      - kong-net
    environment:
      QUARKUS_HTTP_PORT: 8081
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-users:5432/userdb
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - postgres-users

  postgres-users:
    image: postgres:15
    container_name: postgres-users
    networks:
      - kong-net
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - users-db:/var/lib/postgresql/data

volumes:
  users-db: